version: '3.8'

services:
  nginx:
    ports:
      - "3000:80"

  devindocker:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    env_file: .env.dev.local
    command: npm run dev
