version: '3.8'

services:
  nginx:
    extends:
      file: docker-compose.base.yml
      service: nginx
  redis:
    extends:
      file: docker-compose.base.yml
      service: redis
    # ports:
    #   - 6379:6379
  mongodb:
    container_name: mongodb
    extends:
      file: docker-compose.base.yml
      service: mongodb
    user: root
    volumes:
      - mongo-db:/data/db

  devindocker:
    extends:
      file: docker-compose.base.yml
      service: devindocker
    # container_name: devInDocker_dev
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      MONGO_IP: mongodb
      MONGO_PORT: 27017
      MONGO_USER: asd
      MONGO_PASSWORD: asdasd
      APP_PORT: 3000
      environment:
      REDIS_URL: redis
      REDIS_PORT: 6379
      COOKIE_SECRET: "keyboard cat"
    # ports:
    #   - 4000:3000
    env_file: .env
    command: npm run dev

volumes:
  mongo-db:
    name: 'mongo-db'
